---
- hosts: localhost
  become: yes
  vars:
    validate_certs: 'false'

  tasks:
    - name: Security Policy NSX-T Cloud
      nsxt_policy_security_policy:
        hostname: "{{ nsx_server }}"
        username: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        validate_certs: "{{ validate_certs }}"
        state: "{{ state | default('present') }}"
        display_name: "{{ policy_name }}"
        domain_id: "{{ domain_id | default('default') }}"
        category: "{{ category_name | default('Infrastructure') }}"
        rules:
          - action: "ALLOW"
            display_name: "{{ rule_name | default(omit) }}"
            source_groups: ["{{ source_group | default(omit) }}"]
            destination_groups: ["{{ destination_group | default(omit) }}"]
            services: ["ANY"]
      when:
        - nsx_server is defined
        - nsx_username is defined
        - nsx_password is defined
        - validate_certs is defined
        - policy_name is defined
